<a href="https://colab.research.google.com/github/mdjamina/M1_TALA410A_NLP/blob/main/Notebooks_sem2/04_Numpy_intro/NumpyTuto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook in very large part from Sebastian Raschka's STAT 451 class. See his [github repo](https://github.com/rasbt/stat451-machine-learning-fs20) and [course website](http://pages.stat.wisc.edu/~sraschka/teaching/stat451-fs2020/)

---

### 1. NumPy Basics

---

---

NumPy is the base of the scientific Python computing ecosystem

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/numpy-nature-1.png?raw=1" alt="Drawing" style="width: 600px;"/>

Image Source:  Harris, C.R., Millman, K.J., van der Walt, S.J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N.J. and Kern, R., 2020 [Array Programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2). Nature 585, 357–362 (2020). 

---

### Motivation: NumPy is fast!

To provide you with some motivation why learning about and using NumPy is useful, take a look at the speed comparison computing a vector dot product in Python (using lists) versus NumPy (the details will become clear later).

$$
z = \mathbf{x}^\top \mathbf{w} = \sum_i x_i w_i = x_1 \times w_1 + x_2 \times w_2 + ... + x_n \times w_n
$$

In [ ]:
# TODO
# Implement a function that outputs the dot product using a for loop :
def loop_approach(x,w) :
    ...

In [ ]:
big_vectorA = list(range(1000))
big_vectorB = list(range(1000))

%timeit loop_approach(big_vectorA,big_vectorB)

181 µs ± 8.23 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
import numpy as np

def numpy_dotproduct_approach(x, w):
    return x.dot(w)

a = np.array([1., 2., 3.])
b = np.array([4., 5., 6.])

print(numpy_dotproduct_approach(a, b))

32.0


In [ ]:
large_a = np.arange(1000)
large_b = np.arange(1000)

%timeit numpy_dotproduct_approach(large_a, large_b)

2.11 µs ± 94.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### N-dimensional Arrays

* we can think of a one-dimensional NumPy array as a data structure to represent a vector of elements -- you may think of it as a fixed-size Python list where all elements share the same type. 
* Similarly, we can think of a two-dimensional array as a data structure to represent a matrix or a Python list of lists.

In [ ]:
import numpy as np


lst = [[1, 2, 3], [4, 5, 6]]
ary2d = np.array(lst)
ary2d

array([[1, 2, 3],
       [4, 5, 6]])

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/array_1.png?raw=1" alt="Drawing" style="width: 300px;"/>

The `shape` is always a tuple; in the code example above, the two-dimensional object has two *rows* and *three* columns, `(2, 3)`, if we think of it as a matrix representation.

In [ ]:
ary2d.shape

(2, 3)

To return the number of elements in an array, we can use the `size` attribute, as shown below:

In [ ]:
ary2d.size

6

---

### 2. NumPy Array Construction and Indexing

---

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

A very useful function for creating sequences of numbers within a specified range   
NumPy's `arange` function follows the same syntax as Python's `range` objects.  If two arguments are provided, the first argument represents the start value and the second value defines the stop value.

In [ ]:
np.arange(4., 10.)

array([4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1., 10., 2) # with interval

array([1., 3., 5., 7., 9.])

### Array Indexing

Simple NumPy indexing and slicing works similar to Python lists

In [ ]:
ary = np.array([1, 2, 3])
ary[0]

1

In [ ]:
ary[:2]

array([1, 2])

In [ ]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

#ary[0, 0] # guess where

In [ ]:
#ary[-1, -1] # guess where

In [ ]:
#ary[0, 1] # guess where

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/array_2.png?raw=1" alt="Drawing" style="width: 300px;"/>

In [ ]:
#ary[0] 

In [ ]:
#ary[:, 0] 

In [ ]:
#ary[:, :2] 

---

### 3. NumPy Array Math and Universal Functions

---

So why is numpy so useful ? Vectorization.  

While we typically use for-loops if we want to perform arithmetic operations on sequence-like objects, NumPy provides vectorized wrappers for performing element-wise operations implicitly via *ufuncs* -- short for universal functions.  

Ufuncs are implemented in compiled C code and very fast and efficient compared to vanilla Python


In [ ]:
lst = [[1, 2, 3], [4, 5, 6]]

for row_idx, row_val in enumerate(lst):
    for col_idx, col_val in enumerate(row_val):
        lst[row_idx][col_idx] += 1
lst

[[2, 3, 4], [5, 6, 7]]

In [ ]:
ary = np.array([[1, 2, 3], [4, 5, 6]])
ary = np.add(ary, 1)
ary

array([[2, 3, 4],
       [5, 6, 7]])

The ufuncs for basic arithmetic operations are `add`, `subtract`, `divide`, `multiply`, and `exp` (exponential). However, NumPy uses operator overloading so that we can use mathematical operators (`+`, `-`, `/`, `*`, and `**`) directly:

In [ ]:
ary + 1

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
ary**2

array([[ 4,  9, 16],
       [25, 36, 49]])

Often, we want to compute the sum or product of an array element along a given axis. For this purpose, we can use a ufunc's `reduce` operation. By default, `reduce` applies an operation along the first axis (`axis=0`). In the case of a two-dimensional array, we can think of the first axis as the rows of a matrix. Thus, adding up elements along rows yields the column sums of that matrix as shown below:

In [ ]:
ary = np.array([[1, 2, 3], [4, 5, 6]])
np.add.reduce(ary, axis=1)

array([ 6, 15])

While it can be more intuitive to use `reduce` as a more general operation, NumPy also provides shorthands for specific operations such as `product` and `sum`. For example, `sum(axis=0)` is equivalent to `add.reduce`:

In [ ]:
ary.sum(axis=0)

array([5, 7, 9])

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/ufunc.png?raw=1" alt="Drawing" style="width: 600px;"/>

Other useful unary ufuncs are:
    
- `np.mean` (computes arithmetic average)
- `np.std` (computes the standard deviation)
- `np.var` (computes variance)
- `np.sort` (sorts an array)
- `np.argsort` (returns indices that would sort an array)
- `np.min` (returns the minimum value of an array)
- `np.max` (returns the maximum value of an array)
- `np.argmin` (returns the index of the minimum value)
- `np.argmax` (returns the index of the maximum value)
- `np.array_equal` (checks if two arrays have the same shape and elements)

---

### 4. NumPy Broadcasting

---

Broadcasting allows us to perform vectorized operations between two arrays even if their dimensions do not match by creating implicit multidimensional grids.  

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/broadcasting-1.png?raw=1" alt="Drawing" style="width: 500px;"/>


In [ ]:
ary1 = np.array([1, 2, 3]) + 1 
ary1

array([2, 3, 4])

In contrast to what we are used to in linear algebra, we can also add arrays of different shapes. In the example above, we will add a one-dimensional to a two-dimensional array, where NumPy creates an implicit multidimensional grid from the one-dimensional array `ary1`:

In [ ]:
ary2 = np.array([[4, 5, 6], 
                 [7, 8, 9]])

ary2 + ary1

array([[ 6,  8, 10],
       [ 9, 11, 13]])

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/broadcasting-2.png?raw=1" alt="Drawing" style="width: 500px;"/>

---

### 5. Views vs. copies

___

Slicing and indexing yields a *view* of the original array.  This takes up less memory and can be desirable, but be aware that any change you make to the view will modify the original array and vice-versa...

In [ ]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

first_row = ary[0]
first_row += 99
ary

array([[100, 101, 102],
       [  4,   5,   6]])

If you want to handle a slice of the array independently, use `copy`

In [ ]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

second_row = ary[1].copy()
second_row += 99
ary

array([[1, 2, 3],
       [4, 5, 6]])

### Boolean Masks Sidenote

We can use masks to find certain values in an array, to find the amount of correct labels for example.  

In [ ]:
ary = np.array([[1., 2., 3.],
               [4., 5., 6.]])

greaterThan3 = ary > 3
greaterThan3

array([[False, False, False],
       [ True,  True,  True]])

Using these masks, we can select elements given our desired criteria:

In [ ]:
ary[greaterThan3==False]

array([1., 2., 3.])

We can also chain different selection criteria using the logical *and* operator '&' or the logical *or* operator '|'. The example below demonstrates how we can select array elements that are greater than 3 and divisible by 2:

In [ ]:
ary[(ary > 3) & (ary %2 == 0)]

array([4, 6])

---

### 6. Random Number Generators

---

In machine learning and deep learning, we often have to generate arrays of random numbers -- for example, the initial values of our model parameters before optimization or a shuffling of the data.

In [ ]:
np.random.seed(11) # set seed

np.random.rand(3) # same 3 numbers will be generated over and over again

array([0.18026969, 0.01947524, 0.46321853])

In [ ]:
np.random.seed(11)
print(np.random.rand(3)) # random sample 

[0.18026969 0.01947524 0.46321853]


In [ ]:
np.random.randint(0,10, size=(2,2)) # matrix of random integers

array([[9, 0],
       [3, 1]])

Example using KNN.  ALlows for reproducible experiments.  
If you were to use the same seed you would get the same results !

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

np.random.seed(123)

labels = np.array([0]*50 + [1]*50)
data = np.random.rand(100,2)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(data, labels)

assert knn.score(data, labels) == 0.75 #accuracy

We can also create a `RandomState`object, that can also be useful :

In [ ]:
rng1 = np.random.RandomState(seed=11)
rng1.rand(3)

array([0.18026969, 0.01947524, 0.46321853])

---

### 7. Reshaping NumPy Arrays

---

In practice, we often run into situations where existing arrays do not have the *right* shape to perform certain computations (transforming a matrix of pixels into a 1-d vector to feed to a classifier for example). As you might remember from the beginning of this lecture, the size of NumPy arrays is fixed. Fortunately, this does not mean that we have to create new arrays and copy values from the old array to the new one if we want arrays of different shapes -- the size is fixed, but the shape is not. NumPy provides a `reshape` methods that allow us to obtain a view of an array with a different shape. 

In [ ]:
ary1d = np.array([1, 2, 3, 4, 5, 6])
ary2d_view = ary1d.reshape(2, 3)
ary2d_view

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.may_share_memory(ary2d_view, ary1d)

True

While we need to specify the desired elements along each axis, we need to make sure that the reshaped array has the same number of elements as the original one. However, we do not need to specify the number elements in each axis; NumPy is smart enough to figure out how many elements to put along an axis if only one axis is unspecified (by using the placeholder `-1`):

In [ ]:
ary1d.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ary1d.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
ary = np.array([[[1, 2, 3],
                [4, 5, 6]]])

ary.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Sometimes, we are interested in merging different arrays. Unfortunately, there is no efficient way to do this without creating a new array, since NumPy arrays have a fixed size.  
To combine two or more array objects, we can use NumPy's `concatenate` function as shown in the following examples:

In [ ]:
ary = np.array([1, 2, 3])

# stack along the only axis
ary1 = np.concatenate((ary, ary)) 
ary1
#np.may_share_memory(ary, ary1)

array([1, 2, 3, 1, 2, 3])

In [ ]:
ary1 = np.array ([[1,2,3],
                 [4,5,6]])

ary2 = np.array([[1,2,3]])

np.concatenate((ary1, ary2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
ary1 = np.array ([[1,2,3],
                 [4,5,6]])
ary2 = np.array([[1],
                 [2]])

np.concatenate((ary1, ary2), axis=1)

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

---

### 8.Comparison Operators and Masks

___

Boolean masks are `bool`-type arrays (storing `True` and `False` values) that have the same shape as a certain target array. For example, consider the following 4-element array below. Using comparison operators (such as `<`, `>`, `<=`, and `>=`), we can create a Boolean mask of that array which consists of `True` and `False` elements depending on whether a condition is met in the target array (here: `ary`):

In [ ]:
ary = np.array([1, 2, 3, 4, 5])
mask = ary > 2
mask

array([False, False,  True,  True,  True])

Once we have created such a Boolean mask, we can use it to select certain entries from the target array -- those entries that match the condition upon which the mask was created):

In [ ]:
ary[mask]

array([3, 4, 5])

`mask.sum()` Beyond the selection of elements from an array, Boolean masks can also come in handy when we want to count how many elements in an array meet a certain condition:

In [ ]:
mask

array([False, False,  True,  True,  True])

In [ ]:
mask.sum()

3

A related, useful function to assign values to specific elements in an array is the `np.where` function. In the example below, we assign a 1 to all values in the array that are greater than 2 -- and 0, otherwise:

In [ ]:
np.where(ary > 2, 1, 0)

array([0, 0, 1, 1, 1])

In [ ]:
# get indices without the replacement arguments
np.where(ary > 2)

(array([2, 3, 4]),)

There are also 'bit-wise' operators that we can use to specify more complex selection criteria:

In [ ]:
ary = np.array([1, 2, 3, 4, 5])
mask = ary > 2
ary[mask] = 1
ary[~mask] = 0
ary

array([0, 0, 1, 1, 1])

The `~` operator in the example above is one of the logical operators in NumPy:
    
- A: `&`  or `np.bitwise_and`
- Or: `|` or `np.bitwise_or`
- Xor: `^` or `np.bitwise_xor`
- Not: `~` or `np.bitwise_not`

These logical operators allow us to chain an arbitrary number of conditions to create even more "complex" Boolean masks. For example, using the "Or" operator, we can select all elements that are greater than 3 or smaller than 2 as follows:

In [ ]:
ary = np.array([1, 2, 3, 4, 5])
 
mask = (ary > 2) ^ (ary % 2 == 0)
mask

array([False,  True,  True, False,  True])

`~` is the *negate* operator :

In [ ]:
~((ary > 2) ^ (ary % 2 == 0))

array([ True, False, False,  True, False])

### Dealing with predictions example

In [ ]:
preds = np.array([0.3 ,0.9 ,0.2 ,0.68, 0.78])
labels = np.array([0, 1, 0, 0, 1])

mask_preds = np.where(preds > 0.5, 1, 0)
mask_preds

array([0, 1, 0, 1, 1])

In [ ]:
correct_predictions = (mask_preds == labels)
correct_predictions

array([ True,  True,  True, False,  True])

In [ ]:
accuracy = correct_predictions.sum() / len(mask)
accuracy

0.8

---

### 9. Linear Algebra with NumPy

---

Intuitively, we can think of one-dimensional NumPy arrays as data structures that represent row vectors (this differs from the standard column vectors we are used to manipulating in linear algebra...) :

In [ ]:
row_vector = np.array([1, 2, 3])
row_vector

array([1, 2, 3])

Similarly, we can use two-dimensional arrays to create column vectors (a 3x1 matrix basically):

In [ ]:
column_vector = np.array([1, 2, 3]).reshape(-1, 1)
column_vector

array([[1],
       [2],
       [3]])

We can think of a column vector as a matrix consisting only of one column.  
To perform matrix multiplication between matrices, we learned that number of columns of the left matrix must match the number of rows of the matrix to the right. In NumPy, we can perform matrix multiplication via the `matmul` function:

In [ ]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [ ]:
# 2x3 3x1 ==> 2x1
np.matmul(matrix, column_vector)

array([[14],
       [32]])

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/matmul.png?raw=1" alt="Drawing" style="width: 300px;"/>

However numpy can be forgiving regarding dimensions... The following example yields the same result as the matrix-column vector multiplication, except that it returns a one-dimensional array instead of a two-dimensional one:

In [ ]:
# 2x3 3 ==> 2
np.matmul(matrix, row_vector).shape

(2,)

NumPy has a special `dot` function that behaves similar to `matmul` on pairs of one- or two-dimensional arrays

In [ ]:
np.dot(row_vector, row_vector)

14

In [ ]:
np.dot(matrix, row_vector)

array([14, 32])

In [ ]:
np.dot(matrix, column_vector)

array([[14],
       [32]])

You can also use a shortcut operator for `np.dot`, the `@`symbol :

In [ ]:
row_vector @ row_vector

14

In [ ]:
matrix @ row_vector

array([14, 32])

In [ ]:
matrix @ column_vector

array([[14],
       [32]])

NumPy arrays have a handy `transpose` method to transpose matrices if necessary:

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/transpose.png?raw=1" alt="Drawing" style="width: 500px;"/>

In [ ]:
matrix @ matrix.transpose()

array([[14, 32],
       [32, 77]])

<img src="https://github.com/armandstrickernlp/NLP_Inalco/blob/main/Semester2/Notebooks_sem2/04_Numpy_intro/images/numpy-intro/matmatmul.png?raw=1" alt="Drawing" style="width: 500px;"/>

### Multi-Dimensional arrays

These are not traditionally used with numpy, but you will come across them if you do any in deep learning (3-D is generally as far as it goes...)

In [ ]:
n_ary = np.arange(1,41).reshape(2,2,5,-1)
n_ary.shape

(2, 2, 5, 2)

Think of boxes within boxes... Beyond that it's just the same mechanism over and over again, but it starts to become harder to think about as the number of dimensions grows !

---

### 10. Practice Exercises

___

In [ ]:
# Create 2 np arrays and output an array in which every element is the element-wise addition of those 2 arrays

In [ ]:
# Given a numpy array (matrix), how do you get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [ ]:
# Convert a 1-D array to a 3-D array

In [ ]:
# Add a column vector array to a matrix array (as an extra column)

In [ ]:
# From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [ ]:
# Output a 3x3 array of random integers between 0 (inclusive) and 10 (exclusive)

In [ ]:
# Replace the values of the previous array that are lower than 3 with the value 0

In [ ]:
# Given 2 numpy arrays as matrices, output the result of matrix multiplying the 2 matrices (as a numpy array)